### ISSUE TITLE
Inconsistent inertial frame and link frame

### ISSUE THREAD

**Issue by ddliu365** [machines-in-motion/bullet_utils#5]
[Here](https://github.com/machines-in-motion/bullet_utils/blob/7266c05818913e5553bff6bb4b5a78dcb094dc74/src/bullet_utils/wrapper.py#L246), we assume the inertial frame(CoM) and link frame on the `base_link` are consistent while constructing URDF model. However, some cases are not necessarily like this.

I think it might be better to add additional transformation between inertial frame and link frame for more general urdf.

**Comment by jviereck** [comment]
Hi @ddliu365 , the code in question is this

```
            pybullet.resetBasePositionAndOrientation(
                self.robot_id, vec2list(q[:3]), vec2list(q[3:7])
            )
```

I am not sure if I follow your question correctly but this code has nothing to do with the CoM. The `q` and `dq` vector are the generalized coordinates of the robot. The first three entries of the generalized coordinates are as usual the base position and then 4th till 7th coordinates are the quaternion for the orientation.

Why do you think there is an assumption that the com and the link frame are consistent?

**Comment by ddliu365** [comment]
`resetBasePositionAndOrientation` and `getBasePositionAndOrientation` are for the inertia frame in the base_link(p52 in [pybullet guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#)).  However, in pinocchio, `q` is for the link frame for the same base_link in the Urdf.

In solo, I checked the urdf which assumes the link frame and inertial frame are same for the base link(check [here](https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/1208d320c3c40b65b5ee68dffaae775ca1e246ee/src/robot_properties_solo/robot_properties_solo/pre_generated_urdf/solo8.urdf#L11)). Therefore, current code works well.

But for a base_link which has inconsistent link frame and inertial frame, this will cause an issue.

I think it might be better to change `reset_state` and `get_state` like something in the following :

```
def reset_state(self, q, dq):
		vec2list = lambda m: np.array(m.T).reshape(-1).tolist()

		if not self.useFixedBase:

			# conversion between com frame and link frame
			# otherwise base frame should be at CoM in URDF
			stat = p.getDynamicsInfo(self.robot_id, -1)
			pos = stat[3]
			rot = stat[4]
			pos, rot = p.multiplyTransforms(vec2list(q[:3]), vec2list(q[3:7]), pos, rot)

			p.resetBasePositionAndOrientation(self.robot_id, pos, rot)
			
			# Pybullet assumes the base velocity to be aligned with the world frame.
			rot = np.matrix(p.getMatrixFromQuaternion(q[3:7])).reshape((3, 3))
			p.resetBaseVelocity(self.robot_id, vec2list(rot.dot(dq[:3])), vec2list(rot.dot(dq[3:6])))
...
```

```
def get_state(self):
		# Returns a pinocchio like representation of the q, dq matrixes
		q = zero(self.nq)
		dq = zero(self.nv)

		if not self.useFixedBase:
			pos, orn = p.getBasePositionAndOrientation(self.robot_id)

			stat = p.getDynamicsInfo(self.robot_id, -1)
			_pos = stat[3]
			_rot = stat[4]
			_pos, _rot = p.invertTransform(_pos,_rot)
			pos, orn = p.multiplyTransforms(pos, orn, _pos, _rot)

			q[:3, 0] = np.array(pos).reshape(3, 1)
			q[3:7, 0] = np.array(orn).reshape(4, 1)

			vel, orn = p.getBaseVelocity(self.robot_id)
			dq[:3, 0] = np.array(vel).reshape(3, 1)
			dq[3:6, 0] = np.array(orn).reshape(3, 1)

			# Pinocchio assumes the base velocity to be in the body frame -> rotate.
			rot = np.matrix(p.getMatrixFromQuaternion(q[3:7])).reshape((3, 3))
			dq[0:3] = rot.T.dot(dq[0:3])
			dq[3:6] = rot.T.dot(dq[3:6])
...
```

**Comment by MaximilienNaveau** [comment]
Could you give us an example of URDF where the Inertial and link frame are not the same?

**Comment by MaximilienNaveau** [comment]
In the pybullet doc you are referring to the [last paragraph of page 51](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.66ju713r1ecb). 
Last lines of the `getVisualShapeData` paragraph.

It seems you are right that there is something fishy here but the pybullet documentation is not super explicit...

**Comment by ddliu365** [comment]
> Could you give us an example of URDF where the Inertial and link frame are not the same?

Hi,

I think for the solo, you build an absolutely symmetric base.

for example, here is my robot where its inertial frame of base_link is not consistent with its link frame.
```
<robot
  name="humanoid">
	<material name="black">
	    <color rgba="0 0 0 1"/>
	</material>
	<material name="blue">
	    <color rgba="0.6 0.7 0.8 1.0"/>
	</material>
  <link
    name="base_link">
    <inertial>
      <origin
        xyz="-0.027826889135423 -6.26270692615414E-11 -0.0255087787049639"
        rpy="0 0 0" />
      <mass
        value="1.77634423078278" />
      <inertia
        ixx="0.00923177197487557"
        ixy="2.93529499666142E-11"
        ixz="0.000257014494953084"
        iyy="0.00806694145990335"
        iyz="1.16695550105113E-11"
        izz="0.00418937619090114" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://meshes_humanoid/torso.STL" />
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://meshes_humanoid/torso.STL" />
      </geometry>
    </collision>
  </link>
...
</robot>
```

**Comment by MaximilienNaveau** [comment]
@ddliu365 would you mind creating a PR on this?

**Comment by jviereck** [comment]
Thanks @ddliu365 for providing the example. Now it makes more sense. I've reproduced the behavior with a small example. The cube.urdf looks like this (it's a cube shifted on the x axis by 0.4 m):

```
<?xml version="1.0" ?>
<robot name="cube">
  <link name="baseLink">
    <contact>
      <lateral_friction value="1.0"/>
      <rolling_friction value="0.0"/>
      <contact_cfm value="0.0"/>
      <contact_erp value="1.0"/>
    </contact>
    <inertial>
      <origin rpy="0 0 0" xyz="0.4 0 0"/>
       <mass value="1.0"/>
       <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0.4 0 0"/>
      <geometry>
	<mesh filename="cube.obj" scale="1 1 1"/>
      </geometry>
       <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.4 0 0"/>
      <geometry>
	 <box size="1 1 1"/>
      </geometry>
    </collision>
  </link>
</robot>
```

**When loading this urdf at the origin, the cube is shifted along the x axis (as expected):**

```
pos = [0.0, 0, 0.0]
orn = pybullet.getQuaternionFromEuler([0, 0, 0])

robotId = pybullet.loadURDF(
    # From https://github.com/bulletphysics/bullet3/tree/master/data
    'cube.urdf',
    pos, orn,
    flags=pybullet.URDF_USE_INERTIA_FROM_FILE,
    useFixedBase=True
)
```

Leads to:

![image](https://user-images.githubusercontent.com/191719/110497873-d6c34980-80c4-11eb-9b3c-87433eaf8614.png)

**When queering the base position, it reports the position of the inertial frame:**

```
print("Reported base position and orientation.")
print(pybullet.getBasePositionAndOrientation(robotId))

# Reported base position and orientation.
# ((0.4, 0.0, 0.0), (0.0, 0.0, 0.0, 1.0))
```

**When resetting the base, it works on the inertial frame**

```
pos = [0.0, 0, 0.0]
orn = pybullet.getQuaternionFromEuler([0, 0, 0])
pybullet.resetBasePositionAndOrientation(robotId, pos, orn)
```

Leads to

![image](https://user-images.githubusercontent.com/191719/110498493-5fda8080-80c5-11eb-82fc-98df87ac85f5.png)


Note how the cube is now centered at the origin. The inertial frame is at the origin.

**Comment by ddliu365** [comment]
@jviereck This is a good example.

I think the example is not very clear if we align the center of visual cube with com. Here I provide an alternative way to explain the issue.

e.g., we have a box which has a link frame centered at the geometrical origin of cube(visual cube), but its com is not aligned with link frame, say com@(0.4, 0, 0). 
cube. urdf(only change the visual and collision origin compared with above example):
```
<?xml version="1.0" ?>
<robot name="cube">
  <link name="baseLink">
    <contact>
      <lateral_friction value="1.0"/>
      <rolling_friction value="0.0"/>
      <contact_cfm value="0.0"/>
      <contact_erp value="1.0"/>
    </contact>
    <inertial>
      <origin rpy="0 0 0" xyz="0.4 0 0"/>
       <mass value="1.0"/>
       <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
	     <mesh filename="cube.obj" scale="1 1 1"/>
      </geometry>
       <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
	 <box size="1 1 1"/>
      </geometry>
    </collision>
  </link>
</robot>
```
When loading this urdf at the origin, the cube is not shifted along the x axis (pl note that the robot is loaded in pybullet by evaluating the link frame, see p8 in [pybullet guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#)):
```
pos = [0.0, 0, 0.0]
orn = pybullet.getQuaternionFromEuler([0, 0, 0])

robotId = pybullet.loadURDF(
    'cube.urdf',
    pos, orn,
    flags=pybullet.URDF_USE_INERTIA_FROM_FILE,
    useFixedBase=False #since we mostly use floating base, but actually it won't affect the result
)
```
Leads to:
![image](https://user-images.githubusercontent.com/38701021/110718809-ad481200-81d9-11eb-86a5-063999a22aa0.png)
When queering the base position, it reports the position of the inertial frame:
```
print("Reported base position and orientation.")
print(pybullet.getBasePositionAndOrientation(robotId))
# Reported base position and orientation.
# ((0.4, 0.0, 0.0), (0.0, 0.0, 0.0, 1.0))
```
When resetting the base, it works on the inertial frame:
```
pos = [0.0, 0, 0.0]
orn = pybullet.getQuaternionFromEuler([0, 0, 0])
pybullet.resetBasePositionAndOrientation(robotId, pos, orn)
```
Leads to
![image](https://user-images.githubusercontent.com/38701021/110718966-0617aa80-81da-11eb-8018-fc8cbacd6d16.png)

 I actually found this issue when I try to transfer `q` configuration from pinocchio to pybullet.

I can create a PR to fix it @MaximilienNaveau.

**Comment by MaximilienNaveau** [comment]
> I can create a PR to fix it @MaximilienNaveau.

Please do, and thank you very very much for taking the time to explain the issue!
I will review it with @jviereck and merge it asap.

**Comment by ddliu365** [comment]
does anyone know how to fix this error as I am testing the revised code?

The environment I am using:
```
system: ubuntu 18.04
python: 3.6.9
```
```
jack@ubuntu:~/repo/bullet_utils/demos$ python3 demo_simulate_a_robot.py 
pybullet build time: Mar  8 2021 17:24:12
Traceback (most recent call last):
  File "demo_simulate_a_robot.py", line 23, in <module>
    import importlib.resources
ModuleNotFoundError: No module named 'importlib.resources'
```

It seems this is caused by python version.
